### PR TITLE
Version 1.1

### PR DESCRIPTION
**Pull request by Lennong**

### CODE REVIEW

**Comment by dnzbk** [comment]
Ok, let's skip the tests for a while, but please bring back the release pipeline, as it is needed for deployment so that the extension can be picked up by Extension Manager.

**Comment by Lennong** [comment]
image

**Comment by dnzbk** [comment]
So, if there are no tests, please remove [tests.yml](https://github.com/nzbgetcom/Extension-AccessOwnership/blob/main/.github/workflows/tests.yml). We need only [release.yml](https://github.com/nzbgetcom/Extension-AccessOwnership/blob/main/.github/workflows/release.yml) for now.
If your extension requires Python 3.9+ then please update README and manifest.json as they show Python 3.8+ now.

**Comment by dnzbk** [comment]
Or you can just add one simple test like [test_manifest](https://github.com/nzbgetcom/Extension-ExtendedUnrar/blob/fa113c4c5c3c034697d862523b87db8653aefa9f/tests.py#L131) and then you don't have to delete tests.yml.
That would be the best of two worlds I suppose.

**Comment by Lennong** [comment]
It does not require 3.9+. I wrote from another machine that I checked version on so my mistake. I will remove the test.yml.

**Comment by Lennong** [comment]
image

This is ridiculous. Out it goes.

**Comment by dnzbk** [comment]
Ok, I'll merge it as is and then fix the tests.

**Review by dnzbk — APPROVED** [review]

**Pull request merged**
