### PR TITLE
Merging

### PR DESCRIPTION
**Pull request by Lennong**

### CODE REVIEW

**Comment by Lennong** [comment]
No changes made since last release but a merge to get rid of the commits race can be in order?

**Comment by Lennong** [comment]
No, it's ok. Just my OCD that kicks in.. ;)

**Comment by Lennong** [comment]
Actually, how about this; I delete and recreate my repo as it stands today. I simply use present status as starting point without any commit history. Do you need to refork then or will it pick up automatically?

**Comment by Lennong** [comment]
I understand. As of now I am on v1.3 as I have added functionality. How would I go about to push a new version if I am forked from you?

**Comment by Lennong** [comment]
How about this, you delete my contributions here and I'll stay in the 'custom' category for manual installation until a later date? 

I think the users would not benefit having me moving on with developing the extension on my side and adding functionality while an earlier version is hanging here for review. If you pull the version v1.2 in the to the 'repository' of NZBGet Extesion manager and I am moving on in my repository it will effectively block the users from getting the latest version of it via manual installation.

**Comment by phnzb** [comment]
@Lennong Sorry for the troubles, we just want to ensure only verified & tested extension get to users via Extension Manager. This is desired flow:
- We recreate existing repo as fork of your existing repo.
- At some point (when you think it should get into EM) you release an updated version of the extension and you notify us. Don't create PR.
- We update ours fork and release extension for Extension Manager.
- Users will be able to manually install a version from your repository if they wish, but through the Extension Manager they will only be able to install a version that we reviewed and approved.

Please let me know if that's okay with you and if you are ready for release - we are ready for review.

**Comment by Lennong** [comment]
That sounds like a good plan. I have version 1.4 ready with some more improvments. Fork away.. Will now focus more on OS support so take your time. :)

**Pull request closed without merging**
